import assert from "node:assert/strict";
import test from "node:test";
import { createRuntime, normalizeEvent } from "./recording-link-runtime.mjs";
const token="x".repeat(20), phone="15551234567", call="call-1", url="https://assets.aircall.io/recording/call-1";
const config={webhookToken:token,aircallId:"a".repeat(20),aircallKey:"b".repeat(20),mondayToken:"c".repeat(20),host:"127.0.0.1",port:0};
const payload=(extra={})=>JSON.stringify({token,event:"call.comm_assets_generated",data:{id:call,raw_digits:phone,recording_short_url:url,...extra}});
function response(value,{ok=true}={}) { return {ok,json:async()=>value}; }
function mock({matches=["lead-1"]}={}) { const calls=[]; const fetch=async (u,o={})=>{calls.push({u,o}); if(u==='https://api.monday.com/v2'){const q=JSON.parse(o.body).query; if(q.startsWith('mutation'))return response({data:{change_multiple_column_values:{id:"lead-1"}}}); const c=JSON.parse(o.body).variables.c; const hit=matches.includes("lead-1")? [{id:"lead-1",board:{id:"7727339040"},column_values:[{id:c,type:"phone",text:"+1 555 123 4567"}]}]:[]; const second=matches.includes("lead-2")? [{id:"lead-2",board:{id:"7727339040"},column_values:[{id:c,type:"phone",text:"+1 555 123 4567"}]}]:[]; return response({data:{items_page_by_column_values:{items:[...hit,...second]}}});} throw new Error('unexpected aircall read');};return{fetch,calls}; }
async function post(origin,body){const r=await fetch(origin+'/aircall/recording/link-events',{method:'POST',headers:{'content-type':'application/json'},body});return{status:r.status,body:await r.json()};}
test('normalizes only authenticated completed/asset call events',()=>{assert.equal(normalizeEvent(payload(),token)?.callId,call);assert.equal(normalizeEvent(payload({recording_short_url:'http://bad'}),token)?.url,null);assert.equal(normalizeEvent(payload(), 'z'.repeat(20)),null);assert.equal(normalizeEvent(JSON.stringify({token,event:'call.answered',data:{id:call,raw_digits:phone}}),token),null);});
test('writes one recording URL only after exact unique association',async()=>{const m=mock();const r=createRuntime({config,fetchImpl:m.fetch});const a=await r.start();try{const got=await post(`http://${a.host}:${a.port}`,payload());assert.deepEqual(got,{status:202,body:{accepted:true,outcome:'linked'}});const mutation=m.calls.find(x=>x.u==='https://api.monday.com/v2'&&JSON.parse(x.o.body).query.startsWith('mutation'));assert.ok(mutation);const values=JSON.parse(JSON.parse(mutation.o.body).variables.values);assert.deepEqual(values,{link_mm5wtm6z:{url,text:'Aircall recording (expires per Aircall policy)'}});}finally{await r.close();}});
test('zero/ambiguous match never writes',async()=>{for(const [matches,outcome] of [[[], 'no_match'],[['lead-1','lead-2'],'ambiguous_match']]){const m=mock({matches});const r=createRuntime({config,fetchImpl:m.fetch});const a=await r.start();try{assert.deepEqual(await post(`http://${a.host}:${a.port}`,payload()),{status:202,body:{accepted:true,outcome}});assert.equal(m.calls.some(x=>x.u==='https://api.monday.com/v2'&&JSON.parse(x.o.body).query.startsWith('mutation')),false);}finally{await r.close();}}});
